### ISSUE TITLE
Payment Type - Delete

### ISSUE THREAD

**Issue by JonathanPMohan** [partingpets/PartingPets#48]
## User Story

As a user I will want to be able to delete my existing payment types from my User ID. 

## Tech Notes

will need to build the correct Sql calls in the `paymentTypeRepository` and api call in the `paymentTypeController` See previous controllers and repos for examples. 

## Acceptance Criteria

When the `deletePaymentType` calls (api/sql) have been tested and validated, you can then move on to the next card.

**Comment by MCrank** [comment]
Closed PR #61
