### ISSUE TITLE
Payment Type - GET / READ

### ISSUE THREAD

**Issue by colinlwhite** [partingpets/PartingPets#49]
## User Story
- As a developer I need to have an API endpoint to handle Payment Type GET operations for Users of the system 

## Tech Notes
- Inside the Data repository create the `GET` calls to the DB
- Create PaymentType controller and associated GET operation 

## Acceptance Criteria 
- When I send a GET request with the associated user ID
- Then I should receive the appropriate status code of 200
- AND see an object returned from the API with the Payment Types

**Comment by MCrank** [comment]
Closed PR #61
