### ISSUE TITLE
Orders/Invoices - Get

### ISSUE THREAD

**Issue by JonathanPMohan** [partingpets/PartingPets#55]
## User Story

As a developer I need an API endpoint that will retrieve the current orders/invoices from the DB both as a group for admins and also by userID for users.

## Tech Notes

Add Orders/Invoices controller with GET request
Add Orders/Invoices repository to handle GET requests to Database for orders/invoices data
Perform SQL join on orders/invoices, invoiceLineItem and products table to return the required information

## Acceptance Criteria

When I send a GET request to the Orders/invoices GetAllInvoices endpoint
Then I should get a 200 Response code along with the invoices and invoiceLineItems in the DB.

When I send a GET request to the orders/invoices GetInvoicesByUserId endpoint, then I should get a 200 response  code along with the invoices and line items for all users.

**Comment by MCrank** [comment]
Closed PR #68
